apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      restartPolicy: Always
      containers:
      - name: payments
        image: cluster-registry:32000/payments:latest
        # image: payments
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: uri
          - name: PORT
            value: "8080"
          - name: FLASK_APP
            value: wsgi:app
          - name: FLASK_DEBUG
            value: "True"
          - name: GUNICORN_BIND
            value: "0.0.0.0:8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.50"
            memory: "256Mi"
          requests:
            cpu: "0.20"
            memory: "128Mi"
